### ISSUE TITLE
Angular-query-builder for Angular2/4

### ISSUE THREAD

**Issue by nishanth919** [FauzanKhan/angular-query-builder#1]
Hi team,

It looks like this plugin doesn't support for Angular2/4, i might be wrong. Please let me know how to integrate this in Angular2 application. 

FYI: I am not using system.js, instead using webpack.

Regards,
Nishanth P.

**Comment by FauzanKhan** [comment]
Hi Nishanth, 

The plugin was built for Angular 1.x and since I've shifted to react since then, I can't be of much help in porting it to Angular2. However, if you need any help in understanding the internals, I'd be more than happy to help.

**Comment by EAchilles** [comment]
Hi FauzanKhan and Nishanth,

Did anyone rewrite it using angular 2/4?
